openapi: 3.0.0
info:
  title: NodeJS Project
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://localhost:4000/
    description: local server
  - url: http://producation.app/api
    description: production server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /user:
    get:
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Returns a list of users.
          content:
            application/json:
              schema: 
                  type: object
                  properties:                  
                    _id:
                      type: string
                    email:
                      type: string
                  example:
                    _id: "62c2ef14dc41eb120af63460"
                    email: gela@redberry.ge